#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GyakolroWebApp
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Ceg")]
	public partial class CegContextDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertMunkahely(Munkahely instance);
    partial void UpdateMunkahely(Munkahely instance);
    partial void DeleteMunkahely(Munkahely instance);
    partial void InsertDolgozo(Dolgozo instance);
    partial void UpdateDolgozo(Dolgozo instance);
    partial void DeleteDolgozo(Dolgozo instance);
    #endregion
		
		public CegContextDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["CegConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public CegContextDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CegContextDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CegContextDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CegContextDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Munkahely> Munkahelies
		{
			get
			{
				return this.GetTable<Munkahely>();
			}
		}
		
		public System.Data.Linq.Table<Dolgozo> Dolgozos
		{
			get
			{
				return this.GetTable<Dolgozo>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Munkahely")]
	public partial class Munkahely : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _mhID;
		
		private string _munkahelyNev;
		
		private int _szuloID;
		
		private string _mhstatusz;
		
		private EntitySet<Dolgozo> _Dolgozos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmhIDChanging(int value);
    partial void OnmhIDChanged();
    partial void OnmunkahelyNevChanging(string value);
    partial void OnmunkahelyNevChanged();
    partial void OnszuloIDChanging(int value);
    partial void OnszuloIDChanged();
    partial void OnmhstatuszChanging(string value);
    partial void OnmhstatuszChanged();
    #endregion
		
		public Munkahely()
		{
			this._Dolgozos = new EntitySet<Dolgozo>(new Action<Dolgozo>(this.attach_Dolgozos), new Action<Dolgozo>(this.detach_Dolgozos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mhID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int mhID
		{
			get
			{
				return this._mhID;
			}
			set
			{
				if ((this._mhID != value))
				{
					this.OnmhIDChanging(value);
					this.SendPropertyChanging();
					this._mhID = value;
					this.SendPropertyChanged("mhID");
					this.OnmhIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_munkahelyNev", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string munkahelyNev
		{
			get
			{
				return this._munkahelyNev;
			}
			set
			{
				if ((this._munkahelyNev != value))
				{
					this.OnmunkahelyNevChanging(value);
					this.SendPropertyChanging();
					this._munkahelyNev = value;
					this.SendPropertyChanged("munkahelyNev");
					this.OnmunkahelyNevChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_szuloID", DbType="Int NOT NULL")]
		public int szuloID
		{
			get
			{
				return this._szuloID;
			}
			set
			{
				if ((this._szuloID != value))
				{
					this.OnszuloIDChanging(value);
					this.SendPropertyChanging();
					this._szuloID = value;
					this.SendPropertyChanged("szuloID");
					this.OnszuloIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mhstatusz", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string mhstatusz
		{
			get
			{
				return this._mhstatusz;
			}
			set
			{
				if ((this._mhstatusz != value))
				{
					this.OnmhstatuszChanging(value);
					this.SendPropertyChanging();
					this._mhstatusz = value;
					this.SendPropertyChanged("mhstatusz");
					this.OnmhstatuszChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Munkahely_Dolgozo", Storage="_Dolgozos", ThisKey="mhID", OtherKey="mh_id")]
		public EntitySet<Dolgozo> Dolgozos
		{
			get
			{
				return this._Dolgozos;
			}
			set
			{
				this._Dolgozos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Dolgozos(Dolgozo entity)
		{
			this.SendPropertyChanging();
			entity.Munkahely = this;
		}
		
		private void detach_Dolgozos(Dolgozo entity)
		{
			this.SendPropertyChanging();
			entity.Munkahely = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Dolgozo")]
	public partial class Dolgozo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _dolgozoID;
		
		private string _dolgozoNev;
		
		private string _email;
		
		private string _dstatusz;
		
		private int _mh_id;
		
		private EntityRef<Munkahely> _Munkahely;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OndolgozoIDChanging(int value);
    partial void OndolgozoIDChanged();
    partial void OndolgozoNevChanging(string value);
    partial void OndolgozoNevChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OndstatuszChanging(string value);
    partial void OndstatuszChanged();
    partial void Onmh_idChanging(int value);
    partial void Onmh_idChanged();
    #endregion
		
		public Dolgozo()
		{
			this._Munkahely = default(EntityRef<Munkahely>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dolgozoID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int dolgozoID
		{
			get
			{
				return this._dolgozoID;
			}
			set
			{
				if ((this._dolgozoID != value))
				{
					this.OndolgozoIDChanging(value);
					this.SendPropertyChanging();
					this._dolgozoID = value;
					this.SendPropertyChanged("dolgozoID");
					this.OndolgozoIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dolgozoNev", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string dolgozoNev
		{
			get
			{
				return this._dolgozoNev;
			}
			set
			{
				if ((this._dolgozoNev != value))
				{
					this.OndolgozoNevChanging(value);
					this.SendPropertyChanging();
					this._dolgozoNev = value;
					this.SendPropertyChanged("dolgozoNev");
					this.OndolgozoNevChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dstatusz", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string dstatusz
		{
			get
			{
				return this._dstatusz;
			}
			set
			{
				if ((this._dstatusz != value))
				{
					this.OndstatuszChanging(value);
					this.SendPropertyChanging();
					this._dstatusz = value;
					this.SendPropertyChanged("dstatusz");
					this.OndstatuszChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mh_id", DbType="Int NOT NULL")]
		public int mh_id
		{
			get
			{
				return this._mh_id;
			}
			set
			{
				if ((this._mh_id != value))
				{
					if (this._Munkahely.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onmh_idChanging(value);
					this.SendPropertyChanging();
					this._mh_id = value;
					this.SendPropertyChanged("mh_id");
					this.Onmh_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Munkahely_Dolgozo", Storage="_Munkahely", ThisKey="mh_id", OtherKey="mhID", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Munkahely Munkahely
		{
			get
			{
				return this._Munkahely.Entity;
			}
			set
			{
				Munkahely previousValue = this._Munkahely.Entity;
				if (((previousValue != value) 
							|| (this._Munkahely.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Munkahely.Entity = null;
						previousValue.Dolgozos.Remove(this);
					}
					this._Munkahely.Entity = value;
					if ((value != null))
					{
						value.Dolgozos.Add(this);
						this._mh_id = value.mhID;
					}
					else
					{
						this._mh_id = default(int);
					}
					this.SendPropertyChanged("Munkahely");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
